### ISSUE TITLE
"Message to the contributors" field should be bold and email address placeholder should be in the center

### ISSUE THREAD

**Issue by Valenie** [ajency/Giftology#18]
![image](https://cloud.githubusercontent.com/assets/19943710/24184493/35f43708-0ef4-11e7-9169-35f19cba0069.png)

**Comment by ajajrajguru** [comment]
@Valenie Email address textfield is bootstrap tags and it has an overflow for email if it exceeds two lines so that at-least two rows of email are visible cannot start from centre as there will be lot of gap.

![add-email](https://cloud.githubusercontent.com/assets/15607085/24282222/20d65ab8-1084-11e7-8aff-642d7b02e5e9.png)

**Comment by Valenie** [comment]
Retested and fixed.
